name = "infst"
main = "src/index.ts"
compatibility_date = "2025-12-01"

routes = [
  { pattern = "infst.oidehosp.me", custom_domain = true }
]

[triggers]
crons = ["0 3 * * *"]

[vars]
JWT_SECRET = "change-me-in-production"
APP_URL = "https://infst.oidehosp.me"

[[d1_databases]]
binding = "DB"
database_name = "infst-db"
database_id = "eea20de0-326f-4bb0-829f-646772d6b6d0"
migrations_dir = "drizzle"

[assets]
directory = "./public"
